# Generated by Django 4.2.14 on 2025-03-04 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UranelDjangoServer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depense',
            options={'verbose_name': 'Depense', 'verbose_name_plural': 'Depenses'},
        ),
        migrations.AlterModelOptions(
            name='paiement',
            options={'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.AddField(
            model_name='stock',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UranelDjangoServer.customer'),
            preserve_default=False,
        ),
    ]
