# Generated by Django 4.2.14 on 2025-03-07 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UranelDjangoServer', '0004_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UranelDjangoServer.customer'),
            preserve_default=False,
        ),
    ]
