# Generated by Django 4.2.14 on 2025-03-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UranelDjangoServer', '0007_lunette'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lunette',
            name='filter',
        ),
        migrations.AddField(
            model_name='lunette',
            name='filtre',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lunette',
            name='focal',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lunette',
            name='teinte',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
