# Generated by Django 4.2.14 on 2025-03-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UranelDjangoServer', '0008_remove_lunette_filter_lunette_filtre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone1', models.CharField(max_length=15, null=True)),
                ('telephone2', models.CharField(max_length=15, null=True)),
                ('adresse', models.CharField(max_length=15, null=True)),
                ('mail', models.CharField(max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'information',
                'verbose_name_plural': 'informationss',
            },
        ),
    ]
