# Generated by Django 4.2.14 on 2025-03-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UranelDjangoServer', '0010_alter_information_adresse_alter_information_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='LibelleProduct',
            field=models.TextField(),
        ),
    ]
