# Generated by Django 4.2.14 on 2025-03-10 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UranelDjangoServer', '0012_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fonction',
        ),
        migrations.AddField(
            model_name='profile',
            name='site',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='UranelDjangoServer.site'),
            preserve_default=False,
        ),
    ]
