# Generated by Django 4.2.14 on 2025-03-10 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UranelDjangoServer', '0013_remove_profile_fonction_profile_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UranelDjangoServer.site'),
        ),
    ]
